package com.shopease.product.service;

import com.shopease.product.dto.ProductDto;

import java.util.Arrays;
import java.util.List;
import java.util.Map;

public final class ProductCatalogData {

    private ProductCatalogData() {
    }

    public static List<ProductDto> products() {
        return List.of(
                // Electronics
                product(1L, "Electronics", "electronics", null, "boAt Nirvana Ion ANC Earbuds", "boAt", 7999d, 38d, 126, "boAt Official Store", "Brand Store", "Bengaluru, Karnataka", "Hybrid ANC earbuds with dual drivers, long battery backup and low-latency gaming mode for daily music and calls.", images("boat-earbuds-1", "boat-earbuds-2", "boat-earbuds-3"), Map.of("Driver Size", "10mm", "Battery Life", "56 hours", "Water Resistance", "IPX4", "Connectivity", "Bluetooth 5.3"), variants("Color", "Charcoal Black", "Ivory White", "Mint Green"), "12 months", "7-day replacement on manufacturing defects", tags("electronics", "earbuds", "anc", "boat", "audio"), 101L),
                product(1L, "Electronics", "electronics", null, "Samsung Galaxy M15 5G", "Samsung", 17999d, 17d, 84, "Samsung India Store", "Brand Store", "Noida, Uttar Pradesh", "Feature-packed 5G smartphone with Super AMOLED display, massive battery and triple camera setup for reliable everyday performance.", images("m15-1", "m15-2", "m15-3"), Map.of("Display", "6.5-inch FHD+", "RAM", "6 GB", "Storage", "128 GB", "Battery", "6000 mAh"), variants("Color", "Celestial Blue", "Stone Gray"), "12 months", "7-day replacement", tags("electronics", "smartphone", "5g", "samsung"), 102L),
                product(1L, "Electronics", "electronics", null, "LG 1.5 Ton 5 Star Inverter Split AC", "LG", 46990d, 21d, 18, "LG Home Appliances", "Brand Store", "Gurugram, Haryana", "Energy-efficient inverter AC with fast cooling, copper condenser and sleep mode for Indian summer comfort.", images("lg-ac-1", "lg-ac-2", "lg-ac-3"), Map.of("Capacity", "1.5 Ton", "Rating", "5 Star", "Compressor", "Dual Inverter", "Condenser", "Copper"), variants("Color", "White"), "10 years compressor warranty", "7-day return if unopened", tags("electronics", "ac", "inverter", "home-appliance"), 103L),
                product(1L, "Electronics", "electronics", null, "Lenovo IdeaPad Slim 3", "Lenovo", 55990d, 16d, 27, "Lenovo Exclusive Store", "Authorised Seller", "Mumbai, Maharashtra", "Slim everyday laptop powered for work, study and entertainment with fast SSD storage and comfortable typing.", images("lenovo-laptop-1", "lenovo-laptop-2", "lenovo-laptop-3"), Map.of("Processor", "Intel Core i5", "RAM", "16 GB", "Storage", "512 GB SSD", "Display", "15.6-inch FHD"), variants("Color", "Arctic Grey"), "1 year onsite warranty", "7-day replacement", tags("electronics", "laptop", "lenovo", "work-from-home"), 104L),
                product(1L, "Electronics", "electronics", null, "Noise ColorFit Pro 5 Max Smartwatch", "Noise", 9999d, 45d, 65, "Noise India", "Brand Store", "New Delhi, Delhi", "Smartwatch with AMOLED display, health monitoring, Bluetooth calling and multiple sports modes for active lifestyles.", images("noise-watch-1", "noise-watch-2", "noise-watch-3"), Map.of("Display", "1.96-inch AMOLED", "Sensors", "Heart rate, SpO2", "Battery", "7 days", "Water Resistance", "IP68"), variants("Color", "Jet Black", "Rose Pink"), "12 months", "7-day replacement", tags("electronics", "watch", "fitness", "noise"), 105L),

                // Laptops
                product(15L, "Laptops", "laptops", "Gaming", "ASUS TUF Gaming F15", "ASUS", 89990d, 14d, 31, "ASUS India", "Brand Store", "Chennai, Tamil Nadu", "Gaming laptop with high-refresh display, dedicated graphics and strong thermal performance for heavy workloads.", images("/products/laptops/asus1.jpg", "/products/laptops/asus2.jpg", "/products/laptops/asus3.jpg"), Map.of("Processor", "Intel Core i7", "RAM", "16 GB", "Storage", "1 TB SSD", "Graphics", "NVIDIA RTX 4060"), variants("Color", "Mecha Gray"), "12 months", "7-day replacement", tags("laptops", "gaming", "asus", "rtx", "performance"), 1501L),
                product(15L, "Laptops", "laptops", "Ultrabook", "Dell Inspiron 14", "Dell", 67990d, 12d, 44, "Dell Exclusive", "Brand Store", "Bengaluru, Karnataka", "Slim everyday ultrabook with reliable performance, excellent keyboard and strong battery life for students and professionals.", images("/products/laptops/dell1.jpg", "/products/laptops/dell2.jpg", "/products/laptops/dell3.jpg"), Map.of("Processor", "Intel Core i5", "RAM", "16 GB", "Storage", "512 GB SSD", "Display", "14-inch FHD"), variants("Color", "Platinum Silver"), "12 months", "7-day replacement", tags("laptops", "dell", "ultrabook", "office", "study"), 1502L),
                product(15L, "Laptops", "laptops", "Thin and Light", "HP Pavilion 15", "HP", 72990d, 13d, 36, "HP India", "Brand Store", "Noida, Uttar Pradesh", "Balanced thin-and-light laptop with modern design, responsive performance and dependable build quality.", images("/products/laptops/hp1.jpg", "/products/laptops/hp2.jpg", "/products/laptops/hp3.jpg"), Map.of("Processor", "AMD Ryzen 7", "RAM", "16 GB", "Storage", "512 GB SSD", "Display", "15.6-inch FHD"), variants("Color", "Natural Silver"), "12 months", "7-day replacement", tags("laptops", "hp", "thin-and-light", "productivity"), 1503L),
                product(15L, "Laptops", "laptops", "Business", "Lenovo ThinkPad E14", "Lenovo", 74990d, 11d, 29, "Lenovo Business Store", "Authorised Seller", "Mumbai, Maharashtra", "Business-ready laptop with sturdy build, security features and a comfortable typing experience for long work sessions.", images("/products/laptops/lenovo1.jpg", "/products/laptops/lenovo2.jpg", "/products/laptops/lenovo3.jpg"), Map.of("Processor", "Intel Core i5", "RAM", "16 GB", "Storage", "512 GB SSD", "Security", "Fingerprint Reader"), variants("Color", "Black"), "12 months", "7-day replacement", tags("laptops", "lenovo", "thinkpad", "business"), 1504L),
                product(15L, "Laptops", "laptops", "Creator", "Acer Swift X", "Acer", 82990d, 15d, 27, "Acer India", "Authorised Seller", "Hyderabad, Telangana", "Creator-focused laptop with dedicated graphics and color-accurate display for editing, design and content production.", images("/products/laptops/acer1.jpg", "/products/laptops/acer2.jpg", "/products/laptops/acer3.jpg"), Map.of("Processor", "AMD Ryzen 7", "RAM", "16 GB", "Storage", "1 TB SSD", "Graphics", "NVIDIA RTX 3050"), variants("Color", "Steel Gray"), "12 months", "7-day replacement", tags("laptops", "acer", "creator", "editing", "graphics"), 1505L),

                // Fashion
                product(2L, "Fashion", "fashion", "Men's Clothing", "Roadster Men Slim Fit Casual Shirt", "Roadster", 1999d, 55d, 140, "Myntra Fashion Hub", "Marketplace Seller", "Bengaluru, Karnataka", "Smart casual shirt in soft cotton blend with slim fit tailoring ideal for office Fridays and weekend outings.", images("shirt-1", "shirt-2", "shirt-3"), Map.of("Fabric", "Cotton Blend", "Fit", "Slim Fit", "Sleeve", "Full Sleeve", "Pattern", "Solid"), variants("Size", "S", "M", "L", "XL"), "No warranty", "30-day return on unused items", tags("fashion", "shirt", "men", "casual"), 201L),
                product(2L, "Fashion", "fashion", "Women's Clothing", "Biba Women Printed Kurta Set", "Biba", 3499d, 40d, 78, "Biba Fashion Store", "Brand Store", "Jaipur, Rajasthan", "Elegant printed kurta set designed for festive wear with breathable fabric, modern silhouette and matching dupatta.", images("biba-kurta-1", "biba-kurta-2", "biba-kurta-3"), Map.of("Fabric", "Viscose Rayon", "Sleeve", "3/4 Sleeve", "Length", "Knee Length", "Style", "Ethnic"), variants("Size", "M", "L", "XL", "XXL"), "No warranty", "30-day return on unused items", tags("fashion", "kurta", "ethnic", "women"), 202L),
                product(2L, "Fashion", "fashion", "Winter Wear", "H&M Women Oversized Sweatshirt", "H&M", 2799d, 35d, 56, "H&M India", "Brand Store", "Mumbai, Maharashtra", "Relaxed oversized sweatshirt with brushed fleece interior, ribbed cuffs and a clean premium silhouette.", images("sweatshirt-1", "sweatshirt-2", "sweatshirt-3"), Map.of("Fabric", "Cotton Fleece", "Fit", "Oversized", "Neck", "Round Neck", "Season", "Winter"), variants("Size", "S", "M", "L"), "No warranty", "30-day return", tags("fashion", "winterwear", "women", "casual"), 203L),
                product(2L, "Fashion", "fashion", "Formal Wear", "Van Heusen Men Formal Trousers", "Van Heusen", 3299d, 42d, 52, "Van Heusen Studio", "Brand Store", "Chennai, Tamil Nadu", "Sharp formal trousers crafted for long office hours with wrinkle resistance and an elegant tailored finish.", images("trouser-1", "trouser-2", "trouser-3"), Map.of("Fabric", "Poly Viscose", "Fit", "Slim Fit", "Waist Rise", "Mid Rise", "Occasion", "Formal"), variants("Size", "30", "32", "34", "36"), "No warranty", "30-day return", tags("fashion", "formal", "men", "office"), 204L),
                product(2L, "Fashion", "fashion", "Accessories", "Titan Leather Strap Belt", "Titan", 1499d, 33d, 110, "Titan Accessories", "Brand Store", "Pune, Maharashtra", "Premium leather strap belt with polished buckle suitable for formal and semi-formal dressing.", images("belt-1", "belt-2", "belt-3"), Map.of("Material", "Genuine Leather", "Buckle", "Metal", "Width", "35 mm"), variants("Color", "Black", "Brown"), "12 months", "7-day replacement", tags("fashion", "belt", "accessories", "men"), 205L),

                // Footwear
                product(3L, "Footwear", "footwear", "Sports Shoes", "Nike Downshifter 13", "Nike", 6295d, 32d, 44, "Nike India Store", "Brand Store", "Gurugram, Haryana", "Breathable daily running shoes with responsive cushioning and lightweight construction for training and walking.", images("nike-shoe-1", "nike-shoe-2", "nike-shoe-3"), Map.of("Upper Material", "Mesh", "Sole", "Rubber", "Use", "Running/Walking"), variants("Size", "7", "8", "9", "10"), "90 days manufacturing warranty", "15-day exchange on size issues", tags("footwear", "sports-shoes", "nike", "running"), 301L),
                product(3L, "Footwear", "footwear", "Casual Shoes", "Campus Men's Skadi", "Campus", 1799d, 28d, 90, "Campus Footwear", "Brand Store", "Agra, Uttar Pradesh", "Trendy casual sneakers designed for everyday comfort with durable sole grip and easy styling.", images("campus-1", "campus-2", "campus-3"), Map.of("Upper Material", "Synthetic", "Sole", "Phylon", "Closure", "Lace-up"), variants("Size", "6", "7", "8", "9", "10"), "3 months warranty", "15-day exchange", tags("footwear", "casual", "campus", "sneakers"), 302L),
                product(3L, "Footwear", "footwear", "Ethnic", "Liberty Men's Formal Loafers", "Liberty", 2999d, 40d, 33, "Liberty Shoes", "Brand Store", "Delhi, Delhi", "Polished loafers with cushioned insole and sleek finish for weddings, meetings and formal events.", images("loafers-1", "loafers-2", "loafers-3"), Map.of("Upper Material", "Synthetic Leather", "Sole", "TPR", "Closure", "Slip On"), variants("Size", "7", "8", "9", "10"), "90 days warranty", "15-day exchange", tags("footwear", "loafers", "formal", "men"), 303L),
                product(3L, "Footwear", "footwear", "Sandals", "Bata Women Comfort Sandals", "Bata", 2199d, 34d, 66, "Bata India", "Brand Store", "Kolkata, West Bengal", "Comfort sandals with soft footbed, lightweight sole and versatile styling for daily wear.", images("sandals-1", "sandals-2", "sandals-3"), Map.of("Upper Material", "Synthetic", "Sole", "PU", "Style", "Comfort"), variants("Size", "5", "6", "7", "8"), "90 days warranty", "15-day exchange", tags("footwear", "sandals", "women", "comfort"), 304L),
                product(3L, "Footwear", "footwear", "Slippers", "Paragon Men's Flip Flops", "Paragon", 799d, 25d, 120, "Paragon Footwear", "Brand Store", "Kochi, Kerala", "Everyday flip flops with durable straps and cushioned footbed, ideal for casual home and outdoor use.", images("flipflop-1", "flipflop-2", "flipflop-3"), Map.of("Material", "EVA", "Sole", "Rubber", "Style", "Casual"), variants("Size", "6", "7", "8", "9"), "No warranty", "7-day replacement", tags("footwear", "flipflops", "home", "casual"), 305L),

                // Home Appliances
                product(4L, "Home Appliances", "home-appliances", "Kitchen Appliances", "Prestige Air Fryer PAF 4.0", "Prestige", 7995d, 25d, 39, "Prestige Home", "Brand Store", "Pune, Maharashtra", "Digital air fryer with rapid air circulation, multiple presets and detachable basket for healthier cooking.", images("airfryer-1", "airfryer-2", "airfryer-3"), Map.of("Capacity", "4 L", "Power", "1400 W", "Temperature", "80-200 C"), variants("Color", "Black"), "24 months", "7-day replacement", tags("home appliances", "air fryer", "kitchen", "prestige"), 401L),
                product(4L, "Home Appliances", "home-appliances", "Laundry", "Samsung 8 Kg Front Load Washing Machine", "Samsung", 32990d, 18d, 21, "Samsung India Store", "Brand Store", "Noida, Uttar Pradesh", "Front load washing machine with digital inverter, steam wash, and energy efficient drum for daily family use.", images("washer-1", "washer-2", "washer-3"), Map.of("Capacity", "8 Kg", "Type", "Front Load", "Spin Speed", "1400 RPM"), variants("Color", "Silver"), "2 years product warranty / 20 years motor", "7-day return if unopened", tags("home appliances", "washing machine", "laundry", "samsung"), 402L),
                product(4L, "Home Appliances", "home-appliances", "Cleaning", "iRobot Roomba Combo Vacuum", "iRobot", 39999d, 20d, 12, "iRobot India", "Authorised Seller", "Bengaluru, Karnataka", "Robot vacuum and mop combo with smart navigation, scheduling and app control for effortless cleaning.", images("roomba-1", "roomba-2", "roomba-3"), Map.of("Battery", "120 min", "Navigation", "Smart mapping", "Modes", "Vacuum + Mop"), variants("Color", "White"), "12 months", "7-day replacement", tags("home appliances", "robot vacuum", "cleaning", "smart home"), 403L),
                product(4L, "Home Appliances", "home-appliances", "Cooling", "Crompton Desert Air Cooler", "Crompton", 11990d, 30d, 34, "Crompton Appliances", "Brand Store", "Ahmedabad, Gujarat", "High-air delivery desert cooler with honeycomb pads and large water tank for hot Indian summers.", images("cooler-1", "cooler-2", "cooler-3"), Map.of("Tank", "75 L", "Air Delivery", "5500 m3/h", "Type", "Desert Cooler"), variants("Color", "White/Grey"), "12 months", "7-day replacement", tags("home appliances", "cooler", "summer", "crompton"), 404L),
                product(4L, "Home Appliances", "home-appliances", "Heating", "Havells Room Heater", "Havells", 2999d, 28d, 58, "Havells India", "Brand Store", "Delhi, Delhi", "Compact room heater with adjustable thermostat, overheat protection and fast heating coils.", images("heater-1", "heater-2", "heater-3"), Map.of("Power", "2000 W", "Safety", "Overheat protection", "Heat Settings", "2"), variants("Color", "Red"), "12 months", "7-day replacement", tags("home appliances", "heater", "winter", "havells"), 405L),

                // Furniture
                product(5L, "Furniture", "furniture", "Office Chairs", "Furnmill Ergonomic Office Chair", "Furnmill", 12999d, 24d, 46, "Furnmill Furnishings", "Marketplace Seller", "Mumbai, Maharashtra", "Ergonomic office chair with lumbar support, breathable mesh back and adjustable armrests for long working hours.", images("chair-1", "chair-2", "chair-3"), Map.of("Material", "Mesh + Nylon", "Max Load", "120 kg", "Features", "Lumbar support"), variants("Color", "Black", "Grey"), "1 year warranty", "7-day return if unused", tags("furniture", "chair", "office", "ergonomic"), 501L),
                product(5L, "Furniture", "furniture", "Sofas", "Godrej Interio 3-Seater Sofa", "Godrej Interio", 44999d, 22d, 16, "Godrej Interio", "Brand Store", "Bengaluru, Karnataka", "Contemporary 3-seater fabric sofa with premium cushioning, sturdy frame and modern living room appeal.", images("sofa-1", "sofa-2", "sofa-3"), Map.of("Material", "Fabric", "Seating", "3 Seater", "Frame", "Engineered Wood"), variants("Color", "Beige", "Grey"), "3 years frame warranty", "7-day return if unused", tags("furniture", "sofa", "living-room", "godrej"), 502L),
                product(5L, "Furniture", "furniture", "Storage", "Nilkamal Plastic Storage Cabinet", "Nilkamal", 8999d, 35d, 28, "Nilkamal Home", "Brand Store", "Vadodara, Gujarat", "Durable modular storage cabinet with multiple shelves for home organization, files and everyday essentials.", images("cabinet-1", "cabinet-2", "cabinet-3"), Map.of("Material", "Plastic", "Shelves", "4", "Assembly", "Tool-free"), variants("Color", "Brown", "Ivory"), "1 year warranty", "7-day return", tags("furniture", "storage", "cabinet", "nilkamal"), 503L),
                product(5L, "Furniture", "furniture", "Bedroom", "Wakefit King Size Bed", "Wakefit", 28999d, 18d, 11, "Wakefit Furniture", "Brand Store", "Hyderabad, Telangana", "Modern king size bed with engineered wood frame, clean finish and practical under-bed comfort.", images("bed-1", "bed-2", "bed-3"), Map.of("Material", "Engineered Wood", "Size", "King", "Finish", "Walnut"), variants("Color", "Walnut"), "5 years structural warranty", "7-day return if packed", tags("furniture", "bed", "bedroom", "wakefit"), 504L),
                product(5L, "Furniture", "furniture", "Tables", "Urban Ladder Center Table", "Urban Ladder", 15999d, 20d, 24, "Urban Ladder", "Brand Store", "Chennai, Tamil Nadu", "Elegant center table with premium finish, balanced proportions and living room friendly form factor.", images("table-1", "table-2", "table-3"), Map.of("Material", "MDF", "Finish", "Walnut", "Style", "Modern"), variants("Color", "Walnut"), "1 year warranty", "7-day return if unused", tags("furniture", "table", "home-decor", "urban-ladder"), 505L),

                // Groceries
                product(6L, "Groceries", "groceries", "Staples", "Aashirvaad Atta 10 Kg", "Aashirvaad", 520d, 12d, 310, "ITC Foods", "Brand Store", "Kolkata, West Bengal", "Premium whole wheat atta for soft rotis, trusted across Indian households for daily cooking.", images("atta-1", "atta-2", "atta-3"), Map.of("Weight", "10 kg", "Type", "Whole Wheat Flour", "Shelf Life", "6 months"), variants("Pack", "10 Kg"), "No warranty", "3-day return if damaged", tags("groceries", "atta", "staples", "aashirvaad"), 601L),
                product(6L, "Groceries", "groceries", "Beverages", "Bru Instant Coffee Jar", "Bru", 320d, 15d, 170, "Hindustan Unilever", "Brand Store", "Mumbai, Maharashtra", "Strong and aromatic instant coffee jar for quick morning brews and refreshing evening cups.", images("coffee-1", "coffee-2", "coffee-3"), Map.of("Weight", "200 g", "Form", "Instant", "Flavor", "Classic"), variants("Pack", "200 g"), "No warranty", "3-day return if damaged", tags("groceries", "coffee", "beverages", "bru"), 602L),
                product(6L, "Groceries", "groceries", "Snacks", "Kurkure Masala Munch", "Kurkure", 200d, 10d, 240, "PepsiCo India", "Brand Store", "Delhi, Delhi", "Crunchy masala snack pack loved for tea-time munching and quick hunger breaks.", images("kurkure-1", "kurkure-2", "kurkure-3"), Map.of("Weight", "10 x 90 g", "Flavor", "Masala Munch"), variants("Pack", "10 x 90 g"), "No warranty", "3-day return if damaged", tags("groceries", "snacks", "kurkure", "tea-time"), 603L),
                product(6L, "Groceries", "groceries", "Personal Care", "Dettol Hand Wash Refill", "Dettol", 180d, 14d, 260, "Reckitt", "Brand Store", "Gurugram, Haryana", "Anti-bacterial hand wash refill pack with fresh fragrance for daily hygiene and family use.", images("handwash-1", "handwash-2", "handwash-3"), Map.of("Volume", "750 ml", "Type", "Hand Wash Refill"), variants("Pack", "750 ml"), "No warranty", "3-day return if damaged", tags("groceries", "hygiene", "dettol", "personal-care"), 604L),
                product(6L, "Groceries", "groceries", "Dairy", "Amul Ghee 1 Litre", "Amul", 650d, 11d, 96, "Amul India", "Brand Store", "Anand, Gujarat", "Pure cow ghee with rich aroma and premium quality for cooking, sweets and everyday Indian meals.", images("ghee-1", "ghee-2", "ghee-3"), Map.of("Weight", "1 L", "Type", "Cow Ghee"), variants("Pack", "1 L"), "No warranty", "3-day return if damaged", tags("groceries", "ghee", "amul", "dairy"), 605L),

                // Beauty & Personal Care
                product(7L, "Beauty & Personal Care", "beauty-personal-care", "Skin Care", "Mamaearth Vitamin C Face Wash", "Mamaearth", 399d, 20d, 180, "Mamaearth Store", "Brand Store", "Noida, Uttar Pradesh", "Vitamin C enriched face wash designed to brighten skin and gently cleanse daily dirt and oil.", images("facewash-1", "facewash-2", "facewash-3"), Map.of("Volume", "150 ml", "Skin Type", "All Skin Types", "Key Ingredient", "Vitamin C"), variants("Pack", "150 ml"), "No warranty", "7-day return if unopened", tags("beauty", "skincare", "face-wash", "mamaearth"), 701L),
                product(7L, "Beauty & Personal Care", "beauty-personal-care", "Hair Care", "L'Oreal Paris Total Repair Shampoo", "L'Oreal Paris", 499d, 18d, 150, "L'Oreal India", "Brand Store", "Mumbai, Maharashtra", "Nourishing shampoo with repair formula for smoother hair and everyday damage protection.", images("shampoo-1", "shampoo-2", "shampoo-3"), Map.of("Volume", "180 ml", "Hair Type", "Damaged Hair", "Benefit", "Repair"), variants("Pack", "180 ml"), "No warranty", "7-day return if unopened", tags("beauty", "hair-care", "shampoo", "loreal"), 702L),
                product(7L, "Beauty & Personal Care", "beauty-personal-care", "Makeup", "Lakme Forever Matte Lipstick", "Lakme", 499d, 25d, 130, "Lakme Official", "Brand Store", "Bengaluru, Karnataka", "Long-wear matte lipstick with rich pigment, comfortable texture and everyday Indian shades.", images("lipstick-1", "lipstick-2", "lipstick-3"), Map.of("Finish", "Matte", "Wear", "Long Stay", "Shade", "Indian Rose"), variants("Shade", "Indian Rose", "Berry Kiss", "Mocha Brown"), "No warranty", "7-day return if unopened", tags("beauty", "makeup", "lipstick", "lakme"), 703L),
                product(7L, "Beauty & Personal Care", "beauty-personal-care", "Fragrance", "Nivea Body Lotion 600 ml", "Nivea", 599d, 22d, 220, "Nivea India", "Brand Store", "Delhi, Delhi", "Deep moisture body lotion for soft, nourished skin with a light fragrance suitable for Indian weather.", images("lotion-1", "lotion-2", "lotion-3"), Map.of("Volume", "600 ml", "Skin Type", "Dry to Normal", "Benefit", "Moisturizing"), variants("Pack", "600 ml"), "No warranty", "7-day return if unopened", tags("beauty", "body-lotion", "nivea", "fragrance"), 704L),
                product(7L, "Beauty & Personal Care", "beauty-personal-care", "Personal Care", "The Man Company Beard Kit", "The Man Company", 1299d, 30d, 75, "The Man Company", "Brand Store", "Gurugram, Haryana", "Complete grooming kit with beard wash, oil and comb for a polished self-care routine.", images("beard-kit-1", "beard-kit-2", "beard-kit-3"), Map.of("Kit Type", "Grooming", "Contents", "Wash, Oil, Comb"), variants("Pack", "Kit"), "No warranty", "7-day return if unopened", tags("beauty", "grooming", "beard", "men"), 705L),

                // Books
                product(8L, "Books", "books", "Fiction", "The Alchemist", "HarperCollins", 399d, 25d, 180, "HarperCollins India", "Publisher", "Mumbai, Maharashtra", "International bestseller that blends inspiration and adventure in a compact paperback edition for easy reading.", images("alchemist-1", "alchemist-2", "alchemist-3"), Map.of("Format", "Paperback", "Pages", "208", "Language", "English"), variants("Edition", "Paperback"), "No warranty", "7-day replacement for damaged copies", tags("books", "fiction", "bestseller", "paperback"), 801L),
                product(8L, "Books", "books", "Educational", "NCERT Science Class 10", "NCERT", 240d, 15d, 340, "NCERT Publications", "Publisher", "New Delhi, Delhi", "Standard school textbook aligned to curriculum with clear explanations, exercises and illustrations.", images("ncert-1", "ncert-2", "ncert-3"), Map.of("Format", "Paperback", "Pages", "280", "Language", "English"), variants("Edition", "Latest"), "No warranty", "7-day replacement for damaged copies", tags("books", "education", "ncert", "school"), 802L),
                product(8L, "Books", "books", "Self Help", "Atomic Habits", "Penguin", 499d, 30d, 210, "Penguin Random House", "Publisher", "Chennai, Tamil Nadu", "Practical self-improvement book focused on building systems and habits through small daily actions.", images("atomic-1", "atomic-2", "atomic-3"), Map.of("Format", "Paperback", "Pages", "320", "Language", "English"), variants("Edition", "Paperback"), "No warranty", "7-day replacement for damaged copies", tags("books", "self-help", "productivity", "penguin"), 803L),
                product(8L, "Books", "books", "Children", "Wings of Fire", "Scholastic", 350d, 20d, 260, "Scholastic India", "Publisher", "Delhi, Delhi", "Classic autobiography for young readers with motivational storytelling and easy-to-follow chapters.", images("wings-1", "wings-2", "wings-3"), Map.of("Format", "Paperback", "Pages", "232", "Language", "English"), variants("Edition", "Paperback"), "No warranty", "7-day replacement for damaged copies", tags("books", "children", "motivational", "apj"), 804L),
                product(8L, "Books", "books", "Business", "Rich Dad Poor Dad", "Manjul Publishing", 449d, 22d, 140, "Manjul Publishing", "Publisher", "Ahmedabad, Gujarat", "Popular personal finance title explaining money mindset, assets and financial independence for readers.", images("richdad-1", "richdad-2", "richdad-3"), Map.of("Format", "Paperback", "Pages", "336", "Language", "English"), variants("Edition", "Paperback"), "No warranty", "7-day replacement for damaged copies", tags("books", "business", "finance", "manjul"), 805L),

                // Gaming
                product(9L, "Gaming", "gaming", "Consoles", "Sony PlayStation 5 Slim", "Sony", 54990d, 10d, 14, "Sony India", "Brand Store", "Mumbai, Maharashtra", "Latest PS5 slim console with ultra-fast loading, immersive graphics and exclusive next-gen gaming experiences.", images("ps5-1", "ps5-2", "ps5-3"), Map.of("Storage", "1 TB SSD", "Resolution", "4K", "Controller", "DualSense"), variants("Bundle", "Console Only", "Disc Edition"), "1 year warranty", "7-day replacement", tags("gaming", "console", "sony", "ps5"), 901L),
                product(9L, "Gaming", "gaming", "Accessories", "Redgear Pro Wireless Gamepad", "Redgear", 2499d, 32d, 88, "Redgear India", "Brand Store", "Noida, Uttar Pradesh", "Wireless gamepad with responsive triggers, vibration feedback and multi-platform compatibility.", images("gamepad-1", "gamepad-2", "gamepad-3"), Map.of("Connectivity", "2.4 GHz Wireless", "Battery", "10 hours", "Compatibility", "PC / Android"), variants("Color", "Black"), "12 months", "7-day replacement", tags("gaming", "controller", "wireless", "redgear"), 902L),
                product(9L, "Gaming", "gaming", "Accessories", "Cosmic Byte Mechanical Keyboard", "Cosmic Byte", 3999d, 27d, 64, "Cosmic Byte", "Brand Store", "Bengaluru, Karnataka", "Compact mechanical keyboard with RGB lighting, tactile switches and durable gaming build.", images("keyboard-1", "keyboard-2", "keyboard-3"), Map.of("Switch Type", "Blue", "Layout", "Tenkeyless", "Lighting", "RGB"), variants("Color", "Black"), "12 months", "7-day replacement", tags("gaming", "keyboard", "mechanical", "cosmic-byte"), 903L),
                product(9L, "Gaming", "gaming", "Monitors", "Acer Nitro 24-inch Gaming Monitor", "Acer", 15999d, 20d, 31, "Acer India", "Authorised Seller", "Chennai, Tamil Nadu", "Fast refresh rate gaming monitor with low response time and vivid colour output for competitive play.", images("monitor-1", "monitor-2", "monitor-3"), Map.of("Size", "24-inch", "Refresh Rate", "165 Hz", "Response Time", "1 ms"), variants("Panel", "IPS"), "3 years warranty", "7-day replacement", tags("gaming", "monitor", "acer", "esports"), 904L),
                product(9L, "Gaming", "gaming", "Headsets", "Razer BlackShark V2 X", "Razer", 4999d, 15d, 42, "Razer India", "Brand Store", "Gurugram, Haryana", "Lightweight gaming headset with clear microphone pickup and comfortable ear cups for long sessions.", images("headset-1", "headset-2", "headset-3"), Map.of("Connectivity", "Wired", "Microphone", "Noise Cancelling", "Driver", "50 mm"), variants("Color", "Black"), "24 months", "7-day replacement", tags("gaming", "headset", "razer", "audio"), 905L),

                // Sports & Fitness
                product(10L, "Sports & Fitness", "sports-fitness", "Fitness Equipment", "Cult Sport Dumbbell Set", "Cult Sport", 2999d, 25d, 122, "Cult Sport", "Brand Store", "Bengaluru, Karnataka", "Home workout dumbbell set with anti-slip grip for strength training and daily fitness routines.", images("dumbbell-1", "dumbbell-2", "dumbbell-3"), Map.of("Weight", "20 kg set", "Material", "Cast Iron"), variants("Weight", "10 kg", "20 kg"), "6 months warranty", "7-day return if unopened", tags("sports", "fitness", "dumbbells", "cult"), 1001L),
                product(10L, "Sports & Fitness", "sports-fitness", "Apparel", "Decathlon Running T-Shirt", "Decathlon", 699d, 22d, 170, "Decathlon India", "Brand Store", "Hyderabad, Telangana", "Breathable quick-dry running tee for workouts, outdoor runs and gym sessions.", images("runningtee-1", "runningtee-2", "runningtee-3"), Map.of("Fabric", "Polyester", "Fit", "Regular", "Use", "Running"), variants("Size", "S", "M", "L", "XL"), "No warranty", "7-day return if unused", tags("sports", "fitness", "t-shirt", "decathlon"), 1002L),
                product(10L, "Sports & Fitness", "sports-fitness", "Yoga", "PUMA Yoga Mat", "PUMA", 1999d, 30d, 94, "PUMA India", "Brand Store", "Pune, Maharashtra", "Non-slip yoga mat with comfortable cushioning for stretching, meditation and daily practice.", images("yogamat-1", "yogamat-2", "yogamat-3"), Map.of("Thickness", "6 mm", "Material", "TPE", "Grip", "Anti-slip"), variants("Color", "Purple", "Blue"), "12 months", "7-day return if unused", tags("sports", "yoga", "mat", "puma"), 1003L),
                product(10L, "Sports & Fitness", "sports-fitness", "Cycling", "Firefox Mountain Bike Helmet", "Firefox", 2499d, 18d, 51, "Firefox Bikes", "Brand Store", "Delhi, Delhi", "Lightweight cycling helmet with adjustable fit and enhanced safety padding for city rides.", images("helmet-1", "helmet-2", "helmet-3"), Map.of("Size", "M/L", "Material", "ABS Shell", "Ventilation", "Multiple vents"), variants("Color", "Black", "Red"), "12 months", "7-day return if unopened", tags("sports", "fitness", "cycling", "helmet"), 1004L),
                product(10L, "Sports & Fitness", "sports-fitness", "Accessories", "Skip Joy Speed Rope", "Skip Joy", 499d, 18d, 240, "Skip Joy", "Marketplace Seller", "Kolkata, West Bengal", "Adjustable speed skipping rope suitable for cardio, warm-up and home workouts.", images("rope-1", "rope-2", "rope-3"), Map.of("Material", "PVC Cable", "Length", "Adjustable", "Use", "Cardio"), variants("Color", "Black", "Blue"), "No warranty", "7-day return if unopened", tags("sports", "fitness", "rope", "cardio"), 1005L),

                // Home Decor
                product(11L, "Home Decor", "home-decor", "Lighting", "Wipro Smart LED Lamp", "Wipro", 1499d, 22d, 72, "Wipro Lighting", "Brand Store", "Bengaluru, Karnataka", "Smart LED table lamp with adjustable brightness and warm/cool light modes for modern homes.", images("lamp-1", "lamp-2", "lamp-3"), Map.of("Type", "LED Lamp", "Power", "9 W", "Modes", "Warm / Cool"), variants("Color", "White"), "12 months", "7-day replacement", tags("home-decor", "lamp", "lighting", "wipro"), 1101L),
                product(11L, "Home Decor", "home-decor", "Wall Art", "Chumbak Wall Frame Set", "Chumbak", 2499d, 20d, 33, "Chumbak", "Brand Store", "Mumbai, Maharashtra", "Decorative wall frame set with vibrant art for living room and bedroom accent styling.", images("frame-1", "frame-2", "frame-3"), Map.of("Material", "Wooden Frame", "Pieces", "3"), variants("Design", "Abstract", "Modern"), "No warranty", "7-day return if unopened", tags("home-decor", "wall-art", "frames", "chumbak"), 1102L),
                product(11L, "Home Decor", "home-decor", "Curtains", "Portico Printed Curtains", "Portico", 1799d, 28d, 58, "Portico Living", "Brand Store", "Jaipur, Rajasthan", "Premium printed curtains with light-filtering fabric and polished stitching for stylish interiors.", images("curtain-1", "curtain-2", "curtain-3"), Map.of("Fabric", "Polyester", "Set", "2 Panels", "Length", "7 Feet"), variants("Color", "Grey", "Blue"), "No warranty", "7-day return if unused", tags("home-decor", "curtains", "interior", "portico"), 1103L),
                product(11L, "Home Decor", "home-decor", "Rugs", "IKEA Anti-Slip Rug", "IKEA", 2999d, 24d, 26, "IKEA India", "Brand Store", "Hyderabad, Telangana", "Soft anti-slip area rug ideal for bedrooms and living spaces with easy-to-maintain weave.", images("rug-1", "rug-2", "rug-3"), Map.of("Material", "Polyester", "Size", "5x7 ft", "Back", "Anti-slip"), variants("Color", "Beige"), "No warranty", "7-day return if unused", tags("home-decor", "rug", "living-room", "ikea"), 1104L),
                product(11L, "Home Decor", "home-decor", "Clocks", "Home Centre Designer Wall Clock", "Home Centre", 1999d, 27d, 44, "Home Centre", "Brand Store", "Delhi, Delhi", "Designer wall clock that combines premium finish with minimalist contemporary décor styling.", images("clock-1", "clock-2", "clock-3"), Map.of("Material", "Metal", "Diameter", "12 inch"), variants("Color", "Gold"), "1 year warranty", "7-day return if unused", tags("home-decor", "clock", "wall-decor", "home-centre"), 1105L),

                // Jewelry
                product(16L, "Jewelry", "jewelry", "Necklaces", "Tanishq Gold Pendant Set", "Tanishq", 35999d, 9d, 22, "Tanishq India", "Brand Store", "Bengaluru, Karnataka", "Elegant gold pendant set with premium craftsmanship, suitable for festive and occasion wear.", images("jewelry-necklace-1", "jewelry-necklace-2", "jewelry-necklace-3"), Map.of("Material", "22K Gold", "Type", "Pendant Set", "Weight", "8 g", "Stone", "Cubic Zirconia"), variants("Finish", "Yellow Gold"), "1 year manufacturing warranty", "7-day return if unused", tags("jewelry", "gold", "necklace", "tanishq", "fashion"), 1601L),
                product(16L, "Jewelry", "jewelry", "Earrings", "Kalyan Jewellers Stud Earrings", "Kalyan Jewellers", 12999d, 10d, 34, "Kalyan Jewellers", "Brand Store", "Chennai, Tamil Nadu", "Classic stud earrings with a refined finish for daily elegance and special occasions.", images("jewelry-earrings-1", "jewelry-earrings-2", "jewelry-earrings-3"), Map.of("Material", "18K Gold", "Type", "Stud Earrings", "Weight", "4 g", "Stone", "Pearl"), variants("Finish", "Rose Gold"), "1 year manufacturing warranty", "7-day return if unused", tags("jewelry", "earrings", "studs", "kalyan", "daily-wear"), 1602L),
                product(16L, "Jewelry", "jewelry", "Bracelets", "CaratLane Diamond Bracelet", "CaratLane", 24999d, 11d, 18, "CaratLane", "Brand Store", "Mumbai, Maharashtra", "Stylish diamond bracelet designed with a sleek modern profile and delicate sparkle.", images("jewelry-bracelet-1", "jewelry-bracelet-2", "jewelry-bracelet-3"), Map.of("Material", "18K Gold", "Type", "Bracelet", "Stone", "Diamond", "Clasp", "Lobster Clasp"), variants("Finish", "White Gold"), "1 year manufacturing warranty", "7-day return if unused", tags("jewelry", "bracelet", "diamond", "caratlane", "premium"), 1603L),
                product(16L, "Jewelry", "jewelry", "Rings", "Malabar Gold Ring", "Malabar Gold & Diamonds", 18999d, 8d, 29, "Malabar Gold & Diamonds", "Brand Store", "Kochi, Kerala", "Graceful gold ring with timeless design and polished finish for everyday and ceremonial wear.", images("jewelry-ring-1", "jewelry-ring-2", "jewelry-ring-3"), Map.of("Material", "22K Gold", "Type", "Ring", "Weight", "5 g", "Stone", "None"), variants("Size", "14", "16", "18"), "1 year manufacturing warranty", "7-day return if unused", tags("jewelry", "ring", "gold", "malabar", "wedding"), 1604L),
                product(16L, "Jewelry", "jewelry", "Anklets", "PC Jeweller Silver Anklet Pair", "PC Jeweller", 7999d, 12d, 41, "PC Jeweller", "Brand Store", "New Delhi, Delhi", "Sterling silver anklet pair with elegant detailing and lightweight comfort for daily wear.", images("jewelry-anklet-1", "jewelry-anklet-2", "jewelry-anklet-3"), Map.of("Material", "Silver", "Type", "Anklet Pair", "Weight", "12 g", "Stone", "None"), variants("Finish", "Oxidized Silver"), "1 year manufacturing warranty", "7-day return if unused", tags("jewelry", "anklet", "silver", "pcjeweller", "traditional"), 1605L),

                // Mobiles
                product(14L, "Mobiles", "mobiles", "Smartphones", "Apple iPhone 15", "Apple", 79900d, 8d, 42, "Apple India", "Brand Store", "Mumbai, Maharashtra", "A16 Bionic powered iPhone with Dynamic Island, excellent cameras and all-day battery in a premium design.", images("/products/mobiles/iphone1.jpg", "/products/mobiles/iphone2.jpg", "/products/mobiles/iphone3.jpg"), Map.of("Display", "6.1-inch Super Retina XDR", "Storage", "128 GB", "Camera", "48 MP Main", "Battery", "Up to 20 hours video playback"), variants("Color", "Blue", "Black", "Pink"), "12 months", "7-day replacement", tags("mobiles", "smartphone", "iphone", "apple", "5g"), 1401L),
                product(14L, "Mobiles", "mobiles", "Smartphones", "Samsung Galaxy S24", "Samsung", 79999d, 10d, 55, "Samsung India", "Brand Store", "Noida, Uttar Pradesh", "Flagship Samsung smartphone with Galaxy AI features, vibrant AMOLED display and dependable all-round performance.", images("/products/mobiles/sam1.jpg", "/products/mobiles/sam2.jpg", "/products/mobiles/sam3.jpg"), Map.of("Display", "6.2-inch Dynamic AMOLED 2X", "Storage", "256 GB", "Camera", "50 MP Triple Camera", "Battery", "4000 mAh"), variants("Color", "Onyx Black", "Cobalt Violet"), "12 months", "7-day replacement", tags("mobiles", "samsung", "galaxy", "smartphone", "5g"), 1402L),
                product(14L, "Mobiles", "mobiles", "Smartphones", "OnePlus 12R", "OnePlus", 42999d, 12d, 68, "OnePlus Official", "Brand Store", "Bengaluru, Karnataka", "Performance-focused smartphone with smooth AMOLED display, fast charging and flagship-grade everyday experience.", images("/products/mobiles/oneplus1.jpg", "/products/mobiles/oneplus2.jpg", "/products/mobiles/oneplus3.jpg"), Map.of("Display", "6.78-inch AMOLED", "Storage", "256 GB", "Processor", "Snapdragon 8 Gen 2", "Battery", "5500 mAh"), variants("Color", "Cool Blue", "Iron Gray"), "12 months", "7-day replacement", tags("mobiles", "oneplus", "android", "smartphone", "fast-charge"), 1403L),
                product(14L, "Mobiles", "mobiles", "Smartphones", "Xiaomi Redmi Note 13 Pro 5G", "Xiaomi", 27999d, 14d, 96, "Xiaomi India", "Brand Store", "Bengaluru, Karnataka", "Feature-rich mid-range 5G smartphone with high-resolution camera and smooth display for value-focused buyers.", images("/products/mobiles/redmi1.jpg", "/products/mobiles/redmi2.jpg", "/products/mobiles/redmi3.jpg"), Map.of("Display", "6.67-inch AMOLED 120Hz", "Storage", "256 GB", "Camera", "200 MP Main", "Battery", "5100 mAh"), variants("Color", "Arctic White", "Midnight Black"), "12 months", "7-day replacement", tags("mobiles", "xiaomi", "redmi", "5g", "android"), 1404L),
                product(14L, "Mobiles", "mobiles", "Smartphones", "vivo V30 5G", "vivo", 33999d, 11d, 74, "vivo India", "Brand Store", "Greater Noida, Uttar Pradesh", "Stylish 5G smartphone with portrait-focused cameras, slim design and long-lasting battery for daily use.", images("/products/mobiles/vivo1.jpg", "/products/mobiles/vivo2.jpg", "/products/mobiles/vivo3.jpg"), Map.of("Display", "6.78-inch AMOLED 120Hz", "Storage", "256 GB", "Camera", "50 MP Dual Camera", "Battery", "5000 mAh"), variants("Color", "Andaman Blue", "Classic Black"), "12 months", "7-day replacement", tags("mobiles", "vivo", "smartphone", "camera", "5g"), 1405L),

                // Mobile Accessories
                product(12L, "Mobile Accessories", "mobile-accessories", "Chargers", "Ambrane 20W Type-C Fast Charger", "Ambrane", 1499d, 33d, 220, "Ambrane India", "Brand Store", "Noida, Uttar Pradesh", "Fast charging adapter with compact form factor, intelligent protection and daily travel friendly design.", images("charger-1", "charger-2", "charger-3"), Map.of("Output", "20 W", "Port", "USB Type-C", "Protection", "Overcurrent"), variants("Color", "White"), "12 months", "7-day replacement", tags("mobile accessories", "charger", "fast-charge", "ambrane"), 1201L),
                product(12L, "Mobile Accessories", "mobile-accessories", "Cables", "Portronics Sync Cable", "Portronics", 599d, 25d, 280, "Portronics", "Brand Store", "Gurugram, Haryana", "Durable braided cable designed for fast charging and data transfer with long-lasting connectors.", images("cable-1", "cable-2", "cable-3"), Map.of("Length", "1.5 m", "Connector", "USB-A to Type-C", "Material", "Braided"), variants("Color", "Black", "Blue"), "6 months", "7-day replacement", tags("mobile accessories", "cable", "portronics", "type-c"), 1202L),
                product(12L, "Mobile Accessories", "mobile-accessories", "Power Banks", "Mi 10000mAh Power Bank", "Xiaomi", 1999d, 20d, 180, "Mi India", "Brand Store", "Bengaluru, Karnataka", "Compact power bank with fast charging support and reliable capacity for travel and long commutes.", images("powerbank-1", "powerbank-2", "powerbank-3"), Map.of("Capacity", "10000 mAh", "Output", "18 W", "Input", "Type-C"), variants("Color", "Black"), "12 months", "7-day replacement", tags("mobile accessories", "power-bank", "xiaomi", "travel"), 1203L),
                product(12L, "Mobile Accessories", "mobile-accessories", "Cases", "Spigen Rugged Armor Case", "Spigen", 1499d, 22d, 145, "Spigen India", "Authorised Seller", "Chennai, Tamil Nadu", "Shock absorbing rugged mobile cover with premium grip and precise cutouts for daily protection.", images("case-1", "case-2", "case-3"), Map.of("Material", "TPU", "Protection", "Drop Protection"), variants("Color", "Matte Black"), "12 months", "7-day replacement", tags("mobile accessories", "case", "spigen", "cover"), 1204L),
                product(12L, "Mobile Accessories", "mobile-accessories", "Accessories", "Stuffcool Magnetic Car Mount", "Stuffcool", 1299d, 20d, 96, "Stuffcool", "Marketplace Seller", "Mumbai, Maharashtra", "Magnetic dashboard mount with strong hold for navigation, calls and hands-free driving convenience.", images("mount-1", "mount-2", "mount-3"), Map.of("Mount Type", "Magnetic", "Material", "ABS"), variants("Color", "Black"), "6 months", "7-day replacement", tags("mobile accessories", "car-mount", "stuffcool", "navigation"), 1205L),

                // Kitchen Essentials
                product(13L, "Kitchen Essentials", "kitchen-essentials", "Cookware", "Pigeon Pressure Cooker 3 L", "Pigeon", 2199d, 20d, 114, "Pigeon Home", "Brand Store", "Coimbatore, Tamil Nadu", "Induction compatible pressure cooker built for safe, efficient and everyday Indian cooking.", images("cooker-1", "cooker-2", "cooker-3"), Map.of("Capacity", "3 L", "Material", "Aluminium", "Compatibility", "Induction"), variants("Size", "3 L"), "5 years warranty", "7-day return if unused", tags("kitchen essentials", "pressure-cooker", "pigeon", "cookware"), 1301L),
                product(13L, "Kitchen Essentials", "kitchen-essentials", "Drinkware", "Milton Thermosteel Flask", "Milton", 1099d, 25d, 170, "Milton", "Brand Store", "Mumbai, Maharashtra", "Vacuum insulated flask keeps beverages hot or cold for long hours, ideal for office and travel use.", images("flask-1", "flask-2", "flask-3"), Map.of("Capacity", "1 L", "Material", "Stainless Steel", "Insulation", "Double Wall"), variants("Color", "Silver"), "1 year warranty", "7-day return if unused", tags("kitchen essentials", "flask", "travel", "milton"), 1302L),
                product(13L, "Kitchen Essentials", "kitchen-essentials", "Storage", "Cello Glass Storage Jar Set", "Cello", 899d, 18d, 260, "Cello Lifestyle", "Brand Store", "Aurangabad, Maharashtra", "Airtight glass storage jar set perfect for spices, dry fruits and pantry organisation in modern kitchens.", images("jar-1", "jar-2", "jar-3"), Map.of("Material", "Glass", "Pieces", "6", "Lid", "Airtight"), variants("Pack", "6 Piece"), "No warranty", "7-day return if unused", tags("kitchen essentials", "storage", "jars", "cello"), 1303L),
                product(13L, "Kitchen Essentials", "kitchen-essentials", "Appliances", "Philips Mixer Grinder", "Philips", 5995d, 22d, 48, "Philips India", "Brand Store", "Bengaluru, Karnataka", "Powerful mixer grinder for chutneys, masalas and daily kitchen prep with sturdy jars and overload protection.", images("mixer-1", "mixer-2", "mixer-3"), Map.of("Power", "750 W", "Jars", "3", "Speed", "3"), variants("Color", "Black"), "2 years warranty", "7-day replacement", tags("kitchen essentials", "mixer-grinder", "philips", "appliance"), 1304L),
                product(13L, "Kitchen Essentials", "kitchen-essentials", "Bakeware", "Borosil Baking Dish Set", "Borosil", 1599d, 20d, 88, "Borosil India", "Brand Store", "Pune, Maharashtra", "Oven-safe borosilicate baking dish set suitable for casseroles, bakes and everyday cooking needs.", images("dish-1", "dish-2", "dish-3"), Map.of("Material", "Borosilicate Glass", "Pieces", "2", "Oven Safe", "Yes"), variants("Pack", "2 Piece"), "No warranty", "7-day return if unused", tags("kitchen essentials", "bakeware", "borosil", "glass"), 1305L)
        );
    }

    private static ProductDto product(Long categoryId,
                                      String category,
                                      String categorySlug,
                                      String subcategory,
                                      String name,
                                      String brand,
                                      double originalPrice,
                                      double discountPercent,
                                      int stockQuantity,
                                      String sellerName,
                                      String sellerType,
                                      String sellerLocation,
                                      String description,
                                      List<String> images,
                                      Map<String, Object> specs,
                                      List<Map<String, Object>> variants,
                                      String warranty,
                                      String returnPolicy,
                                      List<String> tags,
                                      Long skuNumber) {
        ProductDto dto = new ProductDto();
        dto.categoryId = categoryId;
        dto.categorySlug = categorySlug;
        dto.name = name;
        dto.brand = brand;
        dto.category = category;
        dto.subcategory = subcategory;
        dto.description = description;
        dto.originalPrice = round(originalPrice);
        dto.discountPercent = round(discountPercent);
        dto.price = round(originalPrice * (1d - (discountPercent / 100d)));
        dto.currency = "INR";
        dto.stockQuantity = stockQuantity;
        dto.stockStatus = stockStatus(stockQuantity);
        dto.sku = "SHOP-" + categorySlug.toUpperCase().replace('-', '_') + "-" + skuNumber;
        dto.sellerName = sellerName;
        dto.sellerType = sellerType;
        dto.sellerLocation = sellerLocation;
        dto.images = images;
        dto.specifications = specs;
        dto.variants = variants;
        dto.tags = tags;
        dto.deliveryInfo = Map.of(
                "dispatchTime", stockQuantity > 100 ? "Same day" : "24-48 hours",
                "packaging", "Secure tamper-proof packaging",
                "weight", categorySlug.contains("appliances") ? "2.5 kg" : "500 g",
                "dimensions", categorySlug.contains("furniture") ? "Varies by product" : "Standard retail pack"
        );
        dto.warranty = warranty;
        dto.returnPolicy = returnPolicy;
        dto.sellerId = skuNumber;
        dto.active = true;  // Set products as active by default
        return dto;
    }

    private static List<String> images(String... seeds) {
        return Arrays.stream(seeds)
                .map(seed -> {
                    if (seed == null) return "";
                    if (seed.startsWith("/") || seed.startsWith("http://") || seed.startsWith("https://") || seed.startsWith("data:")) {
                        return seed;
                    }
                    return "https://picsum.photos/seed/" + seed + "/900/900";
                })
                .toList();
    }

    private static List<Map<String, Object>> variants(String labelType, String... values) {
        return Arrays.stream(values)
                .map(value -> Map.<String, Object>of(labelType, value, "stock", 10, "price", 0))
                .toList();
    }

    private static List<String> tags(String... values) {
        return Arrays.stream(values).toList();
    }

    private static String stockStatus(int stock) {
        if (stock <= 0) return "Out of stock";
        if (stock <= 5) return "Low stock";
        return "In stock";
    }

    private static double round(double value) {
        return Math.round(value * 100.0) / 100.0;
    }
}
